// packages/components/src/components-vue/image/index.vue
<template>
  <div :class="cls" :style="$attrs.style ?? {}">
    <img :class="imgCls" :src="src" />
  </div>
</template>

<script>
import classNames from "classnames";

export default {
  inheritAttrs: true,
  props: ["mode", "src"],
  methods: {},
  computed: {
    cls() {
      const cls = classNames(
        "h5-img",
        {
          "h5-img__widthfix": this.mode === "widthFix",
        },
        this.$attrs.className
      );
      return cls;
    },
    imgCls() {
      const imgCls = classNames(
        "h5-img__mode-" +
          (this.mode || "scaleToFill").toLowerCase().replace(/\s/g, "")
      );
      return imgCls
    },
  },
};
</script>

<style lang="less" scoped>
@import "./index.less";
</style>

// packages/components/src/components-h5/image/index.tsx
import * as React from 'react';
import { ImageProps } from '@tarojs/components'
import classNames from 'classnames'
import css from './index.less'

export default (props: ImageProps) => {
  const { className, style, mode, ...rest } = props;
  
  const cls = classNames(
    css.didi,
    'h5-img',
    {
      'h5-img__widthfix': mode === 'widthFix'
    },
    className
  )
  const imgCls = classNames(
    'h5-img__mode-' +
      (mode || 'scaleToFill').toLowerCase().replace(/\s/g, '')
  )

  return (
    <div className={cls} style={style}>
      <img
       className={imgCls}
       {...rest}
      />
    </div>
  )
}
